### ISSUE TITLE
Is there a way to format SQL inside JavaScript files?

### ISSUE THREAD

**Issue by KyleAMathews** [nene/prettier-plugin-sql-cst#12]
E.g. writing queries for SQLite in node.js. Can you teach a plugin to recognize certain objects keys and format the string?

**Comment by nene** [comment]
Not as far as I know.

The Prettier API allows me to do things the other way around. I can tell it to format JavaScript inside SQL. Like this plugin already does with JavaScript inside BigQuery functions. But to my knowledge there is no way to hook into another language (like JavaScript) to format contents of its strings.

The simpler approach to achieve this would be an editor plugin where you could select the SQL you want to format. Unfortunately one won't then have an ability to automatically format the SQL.

**Comment by nene** [comment]
This looks awesome, @Sec-ant.

I basically have the migration to Prettier 3 done. Hopefully I can manage to release it next week.

**Comment by karlhorky** [comment]
@KyleAMathews in case you are open to trying out [`sql-formatter`](https://github.com/sql-formatter-org/sql-formatter) via [`prettier-plugin-sql`](https://github.com/un-ts/prettier/tree/master/packages/sql) before `prettier-plugin-sql-cst` is supported, here's a configuration guide (I'll add this to the docs in both projects over the next days):

- https://github.com/Sec-ant/prettier-plugin-embed/issues/20

**Comment by KyleAMathews** [comment]
@karlhorky nice! Do you plan to support formatting anything other than template literals? The library I use takes the sql string as a key on an object passed to a function.

**Comment by Sec-ant** [comment]
> ah, that's supported? I'll give it a try tomorrow.

Yes, `` /* identifier */ `...` `` and `` identifier`...` `` are supported and you can customize the identifiers :)

**Comment by nene** [comment]
@Sec-ant I have now released prettier-plugin-sql-cst 0.9.0 which has Prettier 3 support.

**Comment by Sec-ant** [comment]
@nene Great news, I'll let you know when it is ready in `prettier-plugin-embed`. :)

**Comment by nene** [comment]
I'm closing this issue as I think the embed plugin solves the problem.

I've added link to the embed plugin to [README](https://github.com/nene/prettier-plugin-sql-cst#how-can-i-format-sql-strings-inside-javascript-files).
