### ISSUE TITLE
command usage

### ISSUE THREAD

**Issue by srqcg** [nene/prettier-plugin-sql-cst#18]
It's perfect!
I wonder if we can format the sql file from the command line using a command like 'prettier-a.sql'

**Comment by nene** [comment]
Just install [prettier](https://prettier.io/docs/en/install) and use it from command line. This library is just a [plugin](https://prettier.io/docs/en/plugins) for prettier. Install it and run like so:

```
prettier --plugin=prettier-plugin-sql-cst
```
