### ISSUE TITLE
Move prettier to peerDependencies?

### ISSUE THREAD

**Issue by mmkal** [nene/prettier-plugin-sql-cst#21]
Hi there! I've only tried out the demo so far, but it looks great. I am looking for a formatter along these lines to use outside of a prettier context. So I'd love to know if a prettier-independent version is something you'd consider. But short of that, moving `prettier` to `peerDependencies` might help make it possible to use outside of prettier (maybe? I haven't tried).

What do you think?

**Comment by nene** [comment]
That's not possible. This plugin relies completely on Prettier library. It builds up a Doc object using Prettier API and then passes that to Prettier, which implements the core of the formatting algorithm.

**Comment by mmkal** [comment]
Got it, thanks.
