### ISSUE TITLE
Apply format for inline SQL string

### ISSUE THREAD

**Issue by peterHakio** [nene/prettier-plugin-sql-cst#25]
In our applications we write raw sql queries like:
```
const query = `
    UPDATE "my_table"
    SET "base" = tmp.new_valu....
`
```
We would love to be able to apply sql formating on these.

A suggestion for a way to detect such queries could be if the string starts with`-- sql`. like this:

```
const query = `-- sql
    UPDATE "my_table"
    SET "base" = tmp.new_valu....
`
```
It could be enabled as a opt in feature, where the trigger string could be a variable the user could set in the config.

Other solution ideas would be appreciated :)

**Comment by nene** [comment]
Please see the [embed](https://github.com/Sec-ant/prettier-plugin-embed) plugin, as mentioned in the [FAQ](https://github.com/nene/prettier-plugin-sql-cst?tab=readme-ov-file#how-can-i-format-sql-strings-inside-javascript-files).
