### ISSUE TITLE
The MySQL statement was incorrectly formatted

### ISSUE THREAD

**Issue by yanglbme** [nene/prettier-plugin-sql-cst#30]
Hello, I have a MySQL statement as follows:

```sql
DELETE p2
FROM
    person AS p1
    JOIN person AS p2 ON p1.email = p2.email
WHERE
    p1.id < p2.id;
```

which was incorrectly formatted as:

```sql
DELETE FROM p2
FROM
    person AS p1
    JOIN person AS p2 ON p1.email = p2.email
WHERE p1.id < p2.id;
```

See https://leetcode.com/problems/delete-duplicate-emails/

**Comment by nene** [comment]
Well, I don't really know what you mean by "incorrect" here.

I guess you are referring to `DELETE` being replaced with `DELETE FROM`.

You can turn off this behavior by [configuring](https://github.com/nene/prettier-plugin-sql-cst?tab=readme-ov-file#configuration) `sqlCanonicalSyntax: false`.

**Comment by yanglbme** [comment]
Thank you very much, the issue has been resolved.
