### ISSUE TITLE
How to enable embedded formatting

### ISSUE THREAD

**Issue by steida** [nene/prettier-plugin-sql-cst#33]
Maybe I'm blind or dumb, but I cannot enable embedded formatting. I just discovered `prettier-plugin-sql`, set it up, and it works. And then I found `prettier-plugin-sql-cst`, and I'm unable to run it for embedded SQL.

Is there some magic setting, or it just doesn't run in monorepo? I don't know; hence, I'm opening issue.

Thank you very much for your work.

**Comment by nene** [comment]
See the FAQ:
https://github.com/nene/prettier-plugin-sql-cst?tab=readme-ov-file#how-can-i-format-sql-strings-inside-javascript-files

**Comment by steida** [comment]
Of course I read that. 

> Use [prettier-plugin-embed](https://github.com/Sec-ant/prettier-plugin-embed) together with prettier-plugin-sql-cst.

I did. It does not work. Sorry if it's obvious.

```ts
yield* sqlite.exec(sql`
    alter table evolu_owner
    drop column merkleTree
  `);
  ```
  
  This SQL wasn't formatted.

**Comment by nene** [comment]
Can't say much with so little information. Most likely there's something in
how you have configured the embed plugin or the sql-cst plugin. But without
seeing the configuration, there's not much I can do.

**Comment by steida** [comment]
@nene Can you please make a working example? I don't know what to set; it's not written in readme.

**Comment by nene** [comment]
I think for the embedded SQL use-case you really only need to add configuration for the embed plugin. Just read the embed plugin docs. Your prettier config file should contain something like this:

```
{
  "plugins": ["prettier-plugin-embed", "prettier-plugin-sql"],
  "embeddedSqlTags: ["sql"],
  "embeddedSqlPlugin": "prettier-plugin-sql-cst",
  "embeddedSqlParser": "sqlite"
}
```

**Comment by steida** [comment]
OK, it was this:

> "embeddedSqlPlugin": "prettier-plugin-sql-cst",

Thank you
