### ISSUE TITLE
`CREATE DATABASE` triggers `Error: Syntax Error: Unexpected "DATABASE"`

### ISSUE THREAD

**Issue by sneko** [nene/prettier-plugin-sql-cst#34]
Hi @nene ,

I don't know if it's intended but when writing `CREATE DATABASE xxxxxxxxx CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; ` it throws the error:
```
Error: Syntax Error: Unexpected "DATABASE"
[error] Was expecting to see: "CONSTRAINT", "EXTERNAL", "FOREIGN", "FULLTEXT", "FUNCTION", "GLOBAL", "INDEX", "LOCAL", "MATERIALIZED", "OR", "PROCEDURE", "RECURSIVE", "SCHEMA", "SEARCH", "SEQUENCE", "SNAPSHOT", "SPATIAL", "TABLE", "TEMP", "TEMPORARY", "TRIGGER", "UNIQUE", "UNLOGGED", "VECTOR", "VIEW", "VIRTUAL", or whitespace
[error] --> /xxxxxxxxxxxx:3:8
[error]   |
[error] 3 | CREATE DATABASE xxxxxxxxx
```

Thank you,

**Comment by nene** [comment]
I suppose you're using MySQL or MariaDB.

The full syntax of either one is not supported yet. Regarding `CREATE DATABASE` and other DDL statements, there's quite a long way to go as seen in here: https://github.com/nene/sql-parser-cst/issues/59

I'm closing this issue as it's a problem in parser, not in the prettier plugin.
