### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by musjj** [nene/prettier-plugin-sql-cst#36]
It'd be nice to have a standalone version that can work on non-Node.js projects, like C++, Go, Rust, etc.

Adding an extra toolchain dependency just for a formatter would be kind of awkward.

**Comment by nene** [comment]
This might be nice. Would you be interested in implementing and maintaining this?

I'm personally pretty unlikely to do it, as my priority is to finish support for PostgreSQL, which is currently the main paint point stopping people from using it.
