### ISSUE TITLE
Readme enhancement for getting started

### ISSUE THREAD

**Issue by TonyGravagno** [nene/prettier-plugin-sql-cst#39]
I have used the inferrinizzard VSCode extension and others. I use Prettier for languages other than SQL - but I'm no Prettier Stud, it's just another tool in my kit that's ignored until I need it ... like today. And I've been a bit confused about the genetic heritage of these SQL parsers/formatters, how they're first general purpose tools, then extensions, then plugins or standalone CLI tools, etc .

So to use this package I have had to back out some older tooling, and I needed some info that I couldn't find here. I hope you can feel a bit of the pain. But thanks for this project and helping to eliminate other pains related to just getting some clean SQL in my editors.

And now for a few Readme enhancement proposals:

### npm

The Readme says "npm install --save-dev prettier prettier-plugin-sql-cst"

DUH on me for an amateur copy/paste. I'm using Pnpm and npm returned an error that sent me off looking for a red herring. If you're using Pnpm, um, use `pnpm` or that command won't do the install.

### Choosing an SQL dialect.

We can store prettier configs in different places. To avoid creating a new file I chose to add configs to package.json.

The Readme says :  

```json
{
  "overrides": [
    {
      "files": ["*.sql"],
      "options": { "parser": "bigquery" }
    }
  ]
}
```

I had to lookup the Prettier docs again to see where that fits. Ahh, this is what goes in package.json:

```json
  "prettier": {
    "overrides": [
      {
        "files": ["*.sql"],
        "options": { "parser":"mariadb" }
      }
    ]
  },
```

Two things to note there.

- Even after a VSCode reload the parser doesn't show any options for "sql", "mysql", "bigquery", etc. Maybe we can call this a bug - or unimplemented feature.
- Adding this isn't all that's required to get Prettier to format SQL. While that's a Prettier thing and not an issue for this package, SQL isn't a first-class language in Prettier, so it is kinda up to plugin providers to provide details to make their plugins operational ... so here we are.

First, if you have (workspace or other) settings.json options related to Prettier-SQL, SQL-Formatter-VScode, or other extensions, comment them out, and disable or uninstall other extensions that provide SQL formatting, then reload the window.

Next, to ensure Prettier is used in VSCode, in settings.json, add this if it's not there already:

```json
  "editor.defaultFormatter": "esbenp.prettier-vscode",
```

Now add this, ideally around other pretter settings, to tell Prettier that it's going to process .sql files :  

```json
  "prettier.documentSelectors": [
    ".sql"
  ],
```

That's actually to register the Prettier formatter with files that have a specific glob pattern. So if you use other extensions like ".sqlite", add them there too. (I dunno if it's required to clean up that as a RegEx pattern but it works as-is for extensions.)

Now tell VSCode that for the "sql" language type, you want to use the "Prettier - Code formatter" extension : 

```json
  "[sql]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
```

You may have that same directive for language `[javascript]` or others.

Finally, and consider this a correction to the current Readme, this is the full config setting for package.json (related to this plugin) :  

```json
  "prettier": {
    "plugins": ["prettier-plugin-sql-cst"],
    "overrides": [
      {
        "files": ["*.sql"],
        "options": { "parser":"mariadb" }
      }
    ]
  },
```

To this point we had only told VSCode that it was going to use Prettier, and told Prettier what files it needs to process. Adding that "plugins" array there tells Prettier that it needs to use a plugin to do the job that we're asking for formatting SQL.

Now give VSCode another reload, just in case.

### How do you know if any of this is working?

After setting all of these configs, try a format. 😉 

Or better, to see what it is, or is not doing - open the Output window and select the Prettier dropdown. On format, the window should show your "inferredParser" (whatever you set above in package config where I have "mariadb"). It should reconfirm that by showing `"parser": "mariadb"` and `"plugins"` with the path to this package. If you don't see that part, it's not using this package.

### Summary

That's all I have to offer and I hope it's accurate and helpful. Please add whatever is useful from this to the Readme, and for anything else, maybe create a wiki?

**Comment by TonyGravagno** [comment]
Side note : Actually I do recognize the genetic heritage of this project. I recently documented the AST for node-sql-parser. I recognized the parser.pegjs and then the note in the Readme clicked about how this all works: Plugin uses parser CST, that was derived from node-sql-parser which was derived from Alibaba. And the .pegjs is either the original Peg.JS or the more recent Peggy.

Since we're here, I'd like to contribute to this (the parser, not so much the plugin). Can we discuss this in a new Discussion area here or in a Discord?

Thanks!

**Comment by nene** [comment]
Thanks for the suggestions. The Prettier setup can indeed be confusing.

I made some updates to the docs, but mostly just liked the official Prettier VSCode docs, which seem to say roughly the same things you're saying. The thing is, I'm not even sure by myself which is the most correct way to configure the Prettier VSCode extension. Like, I personally don't have any of these settings you mention in my VSCode `settings.json` file and formatting of SQL files works just fine. However in the past I remember having problems getting it to work on SQL files. Possibly VSCode has several layers of settings stored in various places... well, I really don't know. Therefore I better just link to the official docs.

**Comment by nene** [comment]
> Even after a VSCode reload the parser doesn't show any options for "sql", "mysql", "bigquery", etc. Maybe we can call this a bug - or unimplemented feature.

Would you care to elaborate. What do you mean by "the parser doesn't show"? How would you expect the parser to show you things? Are you talking about the [sql-parser-cst](https://github.com/nene/sql-parser-cst) library?

**Comment by nene** [comment]
> Since we're here, I'd like to contribute to this (the parser, not so much the plugin). Can we discuss this in a new Discussion area here or in a Discord?

You're welcome. I enabled [discussions in the parser repository](https://github.com/nene/sql-parser-cst/discussions).

**Comment by TonyGravagno** [comment]
> > Even after a VSCode reload the parser doesn't show any options for "sql", "mysql", "bigquery", etc. Maybe we can call this a bug - or unimplemented feature.
> 
> Would you care to elaborate. What do you mean by "the parser doesn't show"? How would you expect the parser to show you things? Are you talking about the [sql-parser-cst](https://github.com/nene/sql-parser-cst) library?

Yeah, that was too vague, sorry. The SQL-related parsers supported by this plugin aren't registered to display in this list:

![image](https://github.com/user-attachments/assets/1ea99184-35d0-45c2-9456-2b16068de685)

**Comment by nene** [comment]
Aha... I see now. I guess one would need to dig into the library that provides the auto-completion of package.json files to figure out how this whole system works. Or alternatively one could install some other prettier plugins and check if the parsers provided by them show up in that list. It might be that this list of possible parsers is very much hardcoded.
