### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by rdsedmundo** [nene/prettier-plugin-sql-cst#4]

**Comment by rdsedmundo** [comment]
@nene the documentation states only SQLite and BigQuery are supported, why did you close the issue as `completed`?

**Comment by nene** [comment]
Well, this "close as completed" is just the default in Github.

Anyway, it's not really a helpful issue per se - especially as it has no description. I know there's no Postgres support, like no support for all other SQL dialects. To even consider adding Postgres formatting, we first need Postgres support in [the parser](https://github.com/nene/sql-parser-cst). I also already know that Postgres support is the most requested feature in the parser... but Postgres is a pretty large language, It'll be a big undertaking.

**Comment by rdsedmundo** [comment]
I understand it's a heavy lift, the idea of the issue is to track the progress, even if it's zero at the moment, and other people can vote and subscribe to it to be notified of how it is going. I didn't write anything in the description because the title was self-explainable.

**Comment by karlhorky** [comment]
For anyone finding this, the issue in the parser is open over here:

- https://github.com/nene/sql-parser-cst/issues/40

**Comment by nene** [comment]
FYI: I have now released version 0.10.0, which includes experimental support for PostgreSQL.

Happy new year.
