### ISSUE TITLE
select top x fails

### ISSUE THREAD

**Issue by cphillips83** [nene/prettier-plugin-sql-cst#6]
Adding `top 15` will break the parser.

EDIT: I realize this is targeted at sqlLite but I've put some pretty large and complex queries in to this thing and `top X` is the only thing it gets tripped up on when testing against MSSQL

**Comment by nene** [comment]
Yes, the `TOP x` syntax is specific to Microsoft flavor of SQL. This plugin only supports SQLite and BigQuery.

Support for Transact-SQL is unlikely to happen any time soon... well, really any time in the foreseeable future as it would take several months of full-time work, and I'd rather like to have a support for Postgres, which is equally huge.
