### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by TimeTerminal** [nene/prettier-plugin-sql-cst#7]
Hi @nene does this plugin support PostgreSQL yet? Or any idea when support will come out for it?

**Comment by nene** [comment]
No. The support will come when I implement a PostgreSQL parser. Which will be... well... who knows... if ever.

**Comment by TimeTerminal** [comment]
Got it 🥲. Thanks for the update. Shall close the issue for now. Really looking forward to the Postgres support in the future though!
