### ISSUE TITLE
[Feature request] Support `If` statement

### ISSUE THREAD

**Issue by acbin** [nene/prettier-plugin-sql-cst#8]
Hi, I use the plugin to format the following sql, but it shows `Syntax Error: Unexpected "if"`

```sql
# Write your MySQL query statement below

select employee_id,
if(employee_id %2=1 and left(name, 1) != 'M', salary, 0) bonus
from Employees
order by 1
```

![图片](https://github.com/nene/prettier-plugin-sql-cst/assets/44314231/e52d7c84-7ccc-47ff-969e-90790d7cd489)

**Comment by nene** [comment]
There's a simple reason for this: [MySQL is not supported](https://github.com/nene/prettier-plugin-sql-cst#limitations-and-development-status).
